name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: make build 
      
    - name: Upload binary as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust_stats_tool_binary
        path: target/release/yijia_ids706_mini_proj7  

    - name: Check formatting
      run: make format

    - name: Lint with Clippy
      run: make lint

    - name: Run tests
      run: make test
