name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: make build-rust
      
    - name: Upload binary as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust_stats_tool_binary
        path: target/release/yijia_ids706_mini_proj8

    - name: Format
      run: make format-rust

    - name: Lint
      run: make lint-rust

    - name: Run tests
      run: make test-rust

    - name: Run Rust performance tests
      run: make perf-test-rust

    - name: Commit and push Rust performance report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add rust_performance.md
        git commit -m "Add Rust performance report" || echo "No changes to commit"
        
        # Stash any remaining changes before pull
        git stash --include-untracked
        
        # Pull latest changes with rebase
        git pull --rebase origin main
        
        # Apply stashed changes back (if there were any)
        git stash pop || echo "Nothing to pop from stash"
        
        # Push the new commit
        git push
